config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  resources :purchases

  resources :items 

  resources :vendors

  resources :deals

  root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/deal.rb
class Deal < ActiveRecord::Base
	belongs_to :vendor
	belongs_to :item
	validates :price, presence: true
	validates :vendor_id, presence: true
	validates :item_id, presence: true
end

app/models/item.rb
class Item < ActiveRecord::Base
	has_many :deals, dependent: :destroy 
	has_many :vendors, through: :deals
	validates :name, uniqueness: true
	validates :name, presence: true

end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	has_and_belongs_to_many :vendors 
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]

  def self.from_omniauth(auth)
		where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
		  user.provider = auth.provider
		  user.uid = auth.uid
		  user.email = auth.info.email
		  user.password = Devise.friendly_token[0,20]
		end
  end
end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
	has_and_belongs_to_many :users
	has_many :deals, dependent: :destroy
	has_many :items, :through => :deals
	validates :name, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
    def facebook
        @user = User.from_omniauth(request.env["omniauth.auth"])
        sign_in_and_redirect @user
    end
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
	def index
		@deals = Deal.all
	end

	def show
		@deal = Deal.find(params[:id])
	end

	def new
		@vendors = Vendor.all
		@items = Item.all
		@deal = Deal.new
	end

	def edit
		@items = Item.all
		@vendors = Vendor.all
		@deal = Deal.find(params[:id])
	end

	def create
		@items = Item.all
		@vendors = Vendor.all
		@deal = Deal.new(deal_params)
		if @deal.save
			redirect_to @deal
		else render 'new'
		end
	end

	def update
		@deal = Deal.find(params[:id])
		if @deal.update(deal_params)
			redirect_to @deal
		else 
			render 'edit'
		end
	end

	def destroy
		@deal = Deal.find(params[:id])
		@deal.destroy

		redirect_to deals_path
	end

	private
	def deal_params
		params.require(:deal).permit(:item_id, :vendor_id, :price)
	end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	
	def index
		@items = Item.all
	end

	def show
		@item = Item.find(params[:id])
	end

	def new
		@item = Item.new
	end

	def edit
		@item = Item.find(params[:id])
	end

	def create
		@item = Item.new(item_params)
		if @item.save
			redirect_to @item
		else render 'new'
		end
	end

	def update
		@item = Item.find(params[:id])

		if @item.update(item_params)
			redirect_to @item
		else
			render 'edit'
		end
	end

	def destroy
		@item = Item.find(params[:id])
		@item.destroy

		redirect_to items_path
	end

	private
	def item_params
		params.require(:item).permit(:name, :description)
	end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :set_purchase, only: [:show, :edit, :update, :destroy]

 

  def index
    @purchases = Purchase.all

  end

  def show
 
  end

  def new
    @purchase = Purchase.new

  end

  def edit
  end

  def create
    @purchase = Purchase.new(purchase_params)
    @purchase.save

  end

  def update
    @purchase.update(purchase_params)

  end

  def destroy
    @purchase.destroy

  end

  private
    def set_purchase
      @purchase = Purchase.find(params[:id])
    end

    def purchase_params
      params.require(:purchase).permit(:deal_id, :user_id, :total_purchases)
    end
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
	def index
		@vendors = Vendor.all
	end

	def show
		@vendor = Vendor.find(params[:id])
	end

	def new
		@vendor = Vendor.new
	end

	def edit
		@vendor = Vendor.find(params[:id])
	end

	def create
		@vendor = Vendor.new(vendor_params)
		if @vendor.save
			redirect_to @vendor
		else render 'new'
		end
	end

	def update
		@vendor = Vendor.find(params[:id])
		if @vendor.update(vendor_params)
			redirect_to @vendor
		else
			render 'edit'
		end
	end

	def destroy
		@vendor = Vendor.find(params[:id])
		@vendor.destroy

		redirect_to vendors_path
	end




	private
	def vendor_params
		params.require(:vendor).permit(:name)
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def omniauth_authorize_path(resource_name, provider)
    send "#{resource_name}_omniauth_authorize_path", provider
  end
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/deals/_form.html.erb
<%= form_for @deal do |f| %>

	<% if @deal.errors.any? %>
		<div id="error_explanation">
			<h2>
				<%= pluralize(@deal.errors.count, "error") %>
				prohibited
				this deal from being saved:
			</h2>
			<ul>
				<% @deal.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 <br>
 
  <p>
    <%= f.label :vendor_id %><br>
    <%= f.collection_select :vendor_id, @vendors, :id, :name, {include_blank: 'Please Select'}, {class: 'selectpicker chosen-select'} %>
  </p>
 
  <p>
    <%= f.label :item %><br>
    <%= f.collection_select :item_id, @items, :id, :name, {include_blank: 'Please Select'}, {class: 'selectpicker chosen-select'} %>
  </p>

  <p>
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
  <% end %>

app/views/deals/edit.html.erb
<h1> Editing Deals</h1>

<%= render 'form' %>
<%= link_to 'Back', deals_path %>

app/views/deals/index.html.erb
<h1>Deals </h1>
<table>
	<tr>
		<th>Vendor</th>
		<th>Item</th>
		<th>Item Description</th>
		<th>Deal Price</th>
		<th colspan="3"></th>
	</tr>

<% @deals.each do |deal| %>
	<tr>
		<td><%= deal.vendor.name %></td>
		<td><%= deal.item.name%></td>
		<td><%= deal.item.description%></td>
		<td><%= deal.price %></td>
		<td><%= link_to 'Show', deal_path(deal)%></td>
		<td><%= link_to 'edit', edit_deal_path(deal)%></td>
		<td><%= link_to 'destroy', deal_path(deal), method: :delete, data: { confirm: 'Are you sure?' } %></td>
	</tr>


	<% end %>
</table>

<%= link_to "New Deal", new_deal_path %>

app/views/deals/new.html.erb
<h1> New Deal </h1>

<%= render 'form' %>
<%= link_to 'Back', deals_path %>

app/views/deals/show.html.erb
<p>
	<strong> Vendor name:</strong>
	<%= @deal.inspect %>
</p>

<p>
	<strong> Item Name: </strong>
	<%= @deal.vendor_id%>
</p>

<%= link_to 'Deals', deals_path %>

app/views/items/_form.html.erb
<%= form_for @item do |f| %>
 
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@item.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @item.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>

  <% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<h2> Items </h2>

<%= link_to 'New Item', new_item_path %>

<% @items.each do |item| %>
	<p><%= item.name %></p>
	<p><%= item.description %></p>
	<p><%= link_to 'Show', item_path(item) %></p>
	<p><%= link_to 'Edit', edit_item_path(item) %></p>
	<p><%= link_to 'Destroy', item_path(item), method: :delete, data: { confirm: 'Are you surrre?' } %></p>
<% end %>

app/views/items/new.html.erb
<h1>hello, world</h1>

<%= render 'form' %>
 
<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p>
	<%= @item.name %>
</p>

<p>
	<%= @item.description %>
</p>

<%= link_to 'All Items', items_path %>
<%= link_to 'Edit', edit_item_path(@item) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SmallTimeGrocer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<a href='/'>Home</a>
<%= link_to 'deals', deals_path %>
<%= link_to 'items', items_path %>
<%= link_to 'vendors', vendors_path %>
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %> 
<%= yield %>

</body>
</html>

app/views/purchases/_form.html.erb
<%= form_for(@purchase) do |f| %>
  <% if @purchase.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@purchase.errors.count, "error") %> prohibited this purchase from being saved:</h2>

      <ul>
      <% @purchase.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :deal_id %><br>
    <%= f.number_field :deal_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :total_purchases %><br>
    <%= f.number_field :total_purchases %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/purchases/edit.html.erb
<h1>Editing Purchase</h1>

<%= render 'form' %>

<%= link_to 'Show', @purchase %> |
<%= link_to 'Back', purchases_path %>

app/views/purchases/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Purchases</h1>

<table>
  <thead>
    <tr>
      <th>Deal</th>
      <th>User</th>
      <th>Total purchases</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @purchases.each do |purchase| %>
      <tr>
        <td><%= purchase.deal_id %></td>
        <td><%= purchase.user_id %></td>
        <td><%= purchase.total_purchases %></td>
        <td><%= link_to 'Show', purchase %></td>
        <td><%= link_to 'Edit', edit_purchase_path(purchase) %></td>
        <td><%= link_to 'Destroy', purchase, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Purchase', new_purchase_path %>

app/views/purchases/new.html.erb
<h1>New Purchase</h1>

<%= render 'form' %>

<%= link_to 'Back', purchases_path %>

app/views/purchases/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Deal:</strong>
  <%= @purchase.deal_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @purchase.user_id %>
</p>

<p>
  <strong>Total purchases:</strong>
  <%= @purchase.total_purchases %>
</p>

<%= link_to 'Edit', edit_purchase_path(@purchase) %> |
<%= link_to 'Back', purchases_path %>

app/views/vendors/_form.html.erb
<%= form_for @vendor do |f| %>
 
  <% if @vendor.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@vendor.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @vendor.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/vendors/edit.html.erb
<h1> Editing Vendor </h1>
<%= render 'form' %>

<%= link_to 'Back', vendors_path %>

app/views/vendors/index.html.erb
<h1> Vendors </h1>
<%= link_to "New Vendor", new_vendor_path %>

<% @vendors.each do |vendor| %>
	<p><%= vendor.name %></p>
	<%= link_to 'Show', vendor_path(vendor) %>
	<%= link_to 'Edit', edit_vendor_path(vendor) %>
	<%= link_to 'Destroy', vendor_path(vendor),
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
<% end %>

app/views/vendors/new.html.erb
<h1> New Vendor </h1>
<%= render 'form' %>

<%= link_to 'Back', vendors_path %>

app/views/vendors/show.html.erb
<p>
	<%= @vendor.name %>
</p>



<%= link_to 'All Vendors', vendors_path %>
<%= link_to 'Edit', edit_vendor_path(@vendor) %>

app/views/welcome/index.html.erb
<h1>hello world</h1>
<%= link_to 'Items', items_path %>
<%= link_to 'Vendors', vendors_path %>
<%= link_to 'Deals', deals_path %>